config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    member do
      get 'thumbnail'
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category, required: true
  attr_accessor :title, :body, :thumbnail

  validates :title, presence: true
  validates :body, presence: true
  validates :category, null: false
  before_create :create_mongo_collections
  after_find :fetch_mongo_data

  private

  def create_mongo_collections
    self.title_oid = Content.create!(body: title, type: 'article_title').id
    self.body_oid = Content.create!(body: body, type: 'article_body').id
    self.thumbnail_oid = Thumbnail.create!(image: thumbnail).id
  end

  def fetch_mongo_data
    self.title = Content.find(title_oid).body
    self.body = Content.find(body_oid).body
    self.thumbnail = Thumbnail.find(thumbnail_oid).image if thumbnail_oid
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
  validates :name, presence: true
end

app/models/content.rb
class Content
  include Mongoid::Document
  field :body, type: String
  field :type, type: String

  validates :body, presence: true
  validates :type, presence: true
end

app/models/thumbnail.rb
class Thumbnail
  include Mongoid::Document
  field :image, type: String
  mount_uploader :image, ThumbnailUploader

  validates :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy, :thumbnail]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def thumbnail
    content = @article.thumbnail.read

    if stale?(etag: content, last_modified: @article.updated_at.utc, public: true)
      send_data content, type: @article.thumbnail.file.content_type, disposition: "inline"
      expires_in 0, public: true
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :published_at, :category_id, :thumbnail)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= form_for article do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error_message| %>
    <li><%= error_message %></li>
  <% end %>
  </ul>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div>
    <%= f.label :published_at %>
    <%= f.datetime_select :published_at %>
  </div>
  <div>
    <%= f.collection_select :category_id, Category.all, :id, :name, prompt: true %>
  </div>
  <div>
    <%= f.file_field :thumbnail %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>articles#edit</h1>
<%= render partial: 'form', locals: {article: @article} %>

app/views/articles/index.html.erb
<h1>articles#index</h1>
<ul>
  <% @articles.each do |article| %>
    <li><%= link_to article.title, article %></li>
  <% end %>
</ul>

app/views/articles/new.html.erb
<h1>articles#new</h1>
<%= render partial: 'form', locals: {article: @article} %>

app/views/articles/show.html.erb
<h1>articles#show</h1>
<dl>
  <dt>サムネイル</dt>
  <dd>
    <% if @article.thumbnail %>
      <%= image_tag thumbnail_article_path(@article), width: "200px" %></dd>
    <% else %>
      No Image
    <% end %>
  <dt>タイトル</dt>
  <dd><%= @article.title %></dd>
  <dt>コンテンツ</dt>
  <dd><%= @article.body %></dd>
</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsWeblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>